server:
  port: 4000

db:
  type: 'mysql'
  port: 3306
  database: 'immiworld'

jwt:
  expiresIn: 3600
  secret: 'topSecret51'

web:
  staticPath: 'http://localhost:4000'
  pageSize: 20

email:
  host: 'smtp.gmail.com'
  port: 465
  auth_user: 'immiworld@gmail.com'
  auth_pass: 'tdwbmumfsmeckhnf1'